DM2518-TakeCare/TakeCare

- App.tsx
- src/pages/create-task.tsx
- src/pages/home-page.tsx
- src/router.tsx
Missing shopping list editable table (component)
> Skeleton for create task page

- src/components/loading-spinner.tsx
- src/pages/playground-page.tsx
Added loading component with example in the playground page
> Loading component

- src/pages/create-task.tsx
closes https://github.com/DM2518-TakeCare/TakeCare/issues/39
> Add animation to create task page

- src/components/table.tsx
- src/pages/create-task.tsx
- src/pages/home-page.tsx
closes #38 
I had to remove the animations since I couldn't get them to work with the dynamic table (and the deadline is tomorrow). But I'd like to try to add them in the future.
> Shopping list table

- src/components/task-details.tsx
- src/components/user-info/user-info.tsx
- src/model/redux/giveHelpState.tsx
- src/model/shared/task-interface.tsx
- src/model/shared/user-interface.tsx
- src/pages/find-task-page.tsx
- src/pages/help-details-page.tsx
- src/pages/task-accepted.tsx
- src/pages/task-completed.tsx
- src/pages/task-created.tsx
- src/pages/tasks-page.tsx
> User task interface

- src/model/shared/user-interface.tsx
- src/model/user-model.tsx
> Add user model

- src/components/snapping-scroll.tsx
> Added rounding for scrollPos

- index.js
- package-lock.json
- package.json
- src/model/firebase.tsx
- src/model/redux/searchTaskState.tsx
- src/model/redux/store.tsx
- src/model/shared/task-interface.tsx
- src/model/task-model.tsx
- src/pages/playground-page.tsx
Task model should be reviewed first.
New code for state task can be found in this commit: https://github.com/DM2518-TakeCare/TakeCare/pull/80/commits/b6a205ba065dbced80ea8fcf6b37bb4be8921b98
> Search task state

- src/model/redux/receiveHelpState.tsx
- src/model/task-model.tsx
Similar to getHelpState but with other variable names. I did not see any need to change/add special things for receiveHelp in comparison to getHelp.
> added receiveHelpState

- App.tsx
- src/model/redux/store.tsx
- src/model/redux/userState.tsx
- src/model/shared/user-interface.tsx
> Redux user state

- src/model/task-model.tsx
Not the best solution, can improve if time
Closing: #92
> Add subscribe functions to task-model

- src/model/redux/giveHelpState.tsx
- src/pages/find-task-page.tsx
- src/pages/help-details-page.tsx
- src/pages/playground-page.tsx
> Update giveHelpState, connect help details

- src/model/redux/receiveHelpState.tsx
- src/model/redux/store.tsx
This needs to be merged in order to do the following issue: #88
> Update receive help state with subscribe action

- App.tsx
- src/components/app-bar.tsx
- src/model/redux/appBarState.tsx
- src/model/redux/store.tsx
- src/model/redux/userState.tsx
- src/pages/create-task.tsx
- src/pages/find-task-page.tsx
Also added appBarState and error handling for CreateTask
closes #87
> Connect create task

- src/components/map.tsx
- src/pages/find-task-page.tsx
This makes the page search tasks every time the page is focused
> Fix map bugs and improve find task page

- App.tsx
- src/model/redux/receiveHelpState.tsx
- src/pages/create-task.tsx
- src/pages/task-accepted.tsx
- src/pages/task-created.tsx
I tried my best... I'm not sure if the subscribe works as it should with unsubscribing and such. The navigation works, at least for me. 
closes #88
> Connect task status

- App.tsx
- src/components/app-bar.tsx
- src/model/redux/giveHelpState.tsx
- src/model/redux/searchTaskState.tsx
- src/model/shared/task-interface.tsx
- src/model/task-model.tsx
- src/pages/find-task-page.tsx
- src/pages/help-details-page.tsx
Make the search use snapshot and run transaction when trying to accept a task
> Find task listener

- src/pages/create-task.tsx
> Add different padding for ios and android

- App.tsx
- src/model/task-model.tsx
- src/pages/home-page.tsx
- src/pages/task-accepted.tsx
> Navigatation receive help

- App.tsx
- src/model/redux/giveHelpState.tsx
- src/model/redux/searchTaskState.tsx
- src/model/task-model.tsx
- src/pages/find-task-page.tsx
- src/pages/register-page.tsx
- src/pages/task-completed.tsx
In addition to making sure the user couldn't go back to a screen when they shouldn't I also did a user test with my boyfriend. I fixed stuff he had comments about, such as making sure you can't see your own tasks in Find Task and having a button in Find Tasks to go to Tasks.
closes #104
> Replace stack and various fixes
